name: PR size labeler

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: CodelyTV/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: 9
          s_max_size: 29
          m_max_size: 99
          l_max_size: 499
          fail_if_xl: false
          files_to_ignore: |
            uv.lock
            *.json
